//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comandos
    {
        public int idComando { get; set; }
        public string Comando { get; set; }
        public string Respuesta { get; set; }
    }
}
